version: "3.3"

services:
  app:
    image: nouchka/sqlite3:latest
    container_name: imageserver-app
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./config.toml:/app/config.toml
      - ./imageserver:/app/imageserver
    ports:
    - 8080:8080
    command:
      - chmod +x /app/imageserver
    working_dir: /app/
    entrypoint: ./imageserver
